/**
 * Copyright (C) 2021-2023 Technology Matters
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see https://www.gnu.org/licenses/.
 */

import { AccountSID } from './twilio';

/**
 * This is the ID of the account HRM stores its data under
 * It is either the Twilio AccountSID or the AccountSID with a suffix
 * Currently in HRM, the AccountSID is still used to authenticate and to look up permissions for authorization, for this reason the HrmAccountId must contain the AccountSID
 * In the future, we may provide a lookup mechanism, or decouple HRM auth from the Twilio AccountSID completely, but for now they need to be linked in their naming.
 * The HrmAccountId is what the data is stored under. This allows us to 'sandbox' data within the same Twilio Account, like for storing data generated by automated tests
 * Currently there is no security enforcing which user can view data from which HRM Accounts under the same Twilio account.
 * This is fine for hiding away unwanted test data but would need addressing if it were to be extended to other use cases
 */
export type HrmAccountId = AccountSID | `${AccountSID}-${string}`;
