#!/usr/bin/env sh

# Execute hrm-service migrations
node ./db-migrate

# Execute resources-service migrations (move once the service lives in it's own container)
node ./node_modules/@tech-matters/resources-service/create-db
node ./node_modules/@tech-matters/resources-service/db-migrate

exec "$@"