#!/usr/bin/env sh

# Execute hrm-service migrations
node ./db-migrate

# Execute resources-service migrations (move once the service lives in it's own container)
cd ./resources-service
node ./db-migrate
cd ..

exec "$@"