# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

version: '3'
services:
  job-processor:
    image: hrm-service
    environment:
      POSTGRES_PORT: 5432
      RDS_HOSTNAME: db
      HRM_RUN_MIGRATIONS: 'true'

    env_file:
      - ../.env.localstack
      - dist/.env

  service:
    image: hrm-service
    ports:
      - '8081:8080'

    environment:
      API_KEY: testApiKey
      PORT: 8080
      POSTGRES_PORT: 5432
      RDS_HOSTNAME: db

    env_file:
      - ../.env.localstack
      - dist/.env

    depends_on:
      - job-processor
