components:
  schemas:
    id:
      type: integer
      format: int32
      example: 27

    ObjectHasId:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'

    SequelizeRecord:
      type: object
      properties:
        createdBy:
          type: string
          example: 'system'
        createdAt:
          type: string
          format: date-time
          example: '2020-03-19T15:03:03.042Z'
        updatedAt:
          type: string
          format: date-time
          example: '2020-04-29T22:18:19.663Z'

    Activity: # Unused?
      type: object
      required:
        - date
        - type
        - text
        - twilioWorkerId
      properties:
        date:
          type: string
          format: date-time
          example: '2020-30-07 18:55:20'
        type:
          type: string
          example: note
        text:
          type: string
          example: Child needs help
        twilioWorkerId:
          type: string
          example: WZd3d289370720216aab7e3dc023e80f5f

  responses:
    UnauthorizedError:
      description: API Key is missing or invalid
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Authorization
security:
  - apiKey: []
