-- liquibase formatted sql

-- changeset liquibase:1642085154105-1
CREATE TABLE "public"."Contacts" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "rawJson" JSONB, "queueName" VARCHAR(255), "twilioWorkerId" VARCHAR(255), "helpline" VARCHAR(255), "number" VARCHAR(255), "channel" VARCHAR(255), "conversationDuration" INTEGER, "caseId" INTEGER, "accountSid" VARCHAR(255), "timeOfContact" TIMESTAMP WITH TIME ZONE, "taskId" VARCHAR(255), "createdBy" VARCHAR(255), "channelSid" VARCHAR(255), "serviceSid" VARCHAR(255), CONSTRAINT "Contacts_pkey" PRIMARY KEY ("id"));

-- changeset liquibase:1642085154105-2
CREATE TABLE "public"."Cases" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "status" VARCHAR(255), "helpline" VARCHAR(255), "info" JSONB, "twilioWorkerId" VARCHAR(255), "accountSid" VARCHAR(255), "createdBy" VARCHAR(255), CONSTRAINT "Cases_pkey" PRIMARY KEY ("id"));

-- changeset liquibase:1642085154105-3
CREATE TABLE "public"."CaseAudits" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "caseId" INTEGER, "twilioWorkerId" VARCHAR(255), "previousValue" JSONB, "newValue" JSONB, "accountSid" VARCHAR(255), "createdBy" VARCHAR(255), CONSTRAINT "CaseAudits_pkey" PRIMARY KEY ("id"));

-- changeset liquibase:1642085154105-4
CREATE TABLE "public"."PostSurveys" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "accountSid" VARCHAR(255), "taskId" VARCHAR(255), "contactTaskId" VARCHAR(255), "data" JSONB, CONSTRAINT "PostSurveys_pkey" PRIMARY KEY ("id"));

-- changeset liquibase:1642085154105-5
CREATE TABLE "public"."CSAMReports" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "accountSid" VARCHAR(255), "twilioWorkerId" VARCHAR(255), "csamReportId" VARCHAR(255), "contactId" INTEGER, CONSTRAINT "CSAMReports_pkey" PRIMARY KEY ("id"));

-- changeset liquibase:1642085154105-6
CREATE TABLE "public"."SequelizeMeta" ("name" VARCHAR(255) NOT NULL, CONSTRAINT "SequelizeMeta_pkey" PRIMARY KEY ("name"));

-- changeset liquibase:1642085154105-7
ALTER TABLE "public"."CSAMReports" ADD CONSTRAINT "CSAMReports_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "public"."Contacts" ("id") ON UPDATE CASCADE ON DELETE SET NULL;

-- changeset liquibase:1642085154105-8
ALTER TABLE "public"."CaseAudits" ADD CONSTRAINT "CaseAudits_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "public"."Cases" ("id") ON UPDATE CASCADE ON DELETE SET NULL;

-- changeset liquibase:1642085154105-9
ALTER TABLE "public"."Contacts" ADD CONSTRAINT "Contacts_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "public"."Cases" ("id") ON UPDATE CASCADE ON DELETE SET NULL;

