/**
 * Copyright (C) 2021-2026 Technology Matters
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see https://www.gnu.org/licenses/.
 */

export type ColumnClassification = 'import' | 'ignore';

export const KNOWN_CALL_REPORT_COLUMNS: Readonly<Record<string, ColumnClassification>> = {
  '211Region': 'ignore',
  'Call Information - Call Direction': 'import',
  'Call Information - Call Type': 'import',
  CallDateAndTimeEnd: 'ignore',
  CallDateAndTimeStart: 'import',
  CallLength: 'ignore',
  'Caller Demographics - 988 referral': 'import',
  'Caller Demographics - Age Range': 'import',
  'Caller Demographics - Ethnicity': 'import',
  'Caller Demographics - Gender': 'import',
  'Caller Demographics - Military Status': 'import',
  'Caller Demographics - Other Race': 'ignore',
  'Caller Demographics - Pronouns': 'import',
  'Caller Demographics - Race': 'import',
  CallerAddress: 'ignore',
  CallerLastName: 'ignore',
  CallerMiddleName: 'ignore',
  CallerName: 'import',
  CallerNum: 'ignore',
  CallersFeedback: 'ignore',
  CensusDivision: 'ignore',
  CensusReportingArea: 'ignore',
  CensusTrack: 'ignore',
  CityName: 'import',
  CountryName: 'ignore',
  CountyName: 'import',
  'Crisis Response - Outcomes from Crisis Response': 'ignore',
  'Demographics - Gender': 'ignore',
  EmailAddress: 'ignore',
  EnteredByName: 'ignore',
  EnteredByWorkerNum: 'ignore',
  EnteredOn: 'ignore',
  Feedback: 'ignore',
  FeedbackFromPhoneWorkerName: 'ignore',
  FeedbackFromPhoneWorkerNum: 'ignore',
  FeedbackStatus: 'ignore',
  'Follow up Outcome - Did you connect with caller?': 'ignore',
  // Trailing space trimmed to match the parsed header: csv-parse's trim:true
  // trims column names too, not just values.
  'Follow up Outcome - If a referral was given did you use that referral?': 'ignore',
  'Follow up Outcome - Is this a follow-up call?': 'ignore',
  'Follow up Outcome - Was caller satisfied - No': 'ignore',
  'Follow up Outcome - Was the caller satisfied?': 'import',
  GeoAssignment: 'ignore',
  GeoCode: 'ignore',
  IPAddress: 'ignore',
  'Incoming Call Information - Additional Supports Contacted': 'ignore',
  'Incoming Call Information - Additional Supports Other - Please specify': 'ignore',
  'Incoming Call Information - Do you want a call back': 'import',
  'Incoming Call Information - Have you been directly impacted by COVID-19': 'ignore',
  'Incoming Call Information - Have you been directly impacted by substance use?':
    'import',
  'Incoming Call Information - Hear about Warmline Other - Please specify': 'ignore',
  'Incoming Call Information - How did you hear about the Warmline?': 'import',
  'Incoming Call Information - If yes please explain how you have been impacted by COVID':
    'ignore',
  'Incoming Call Information - Indicators of Crisis (If applicable suicidal ideation threatening or harmful statements)':
    'ignore',
  LinkedToCallReportNum: 'ignore',
  Narrative: 'ignore',
  Neighborhood: 'ignore',
  'Non-Crisis Response - Outcomes from Non-Crisis Response': 'ignore',
  'Non-Crisis Response - Was Caller Satisfied?': 'import',
  'Non-Crisis Response - Was caller satisfied - No': 'ignore',
  OrgNum: 'ignore',
  'Outbound Call Information - Reason for Outbound Call': 'ignore',
  'Outbound Call Information - Reason for Outbound Call Other - Please specify': 'ignore',
  PhoneExtension: 'ignore',
  PhoneNumberFull: 'import',
  PhoneType: 'ignore',
  PhoneWorkerName: 'import',
  PhoneWorkerNum: 'ignore',
  PostalCode: 'ignore',
  'Referrals - Other - Please specify': 'ignore',
  'Referrals - Type of Resource': 'import',
  'Referrals - Where did you refer caller?': 'ignore',
  ReferralsMade: 'ignore',
  ReportVersion: 'ignore',
  ReportVersionNum: 'ignore',
  Reviewed: 'ignore',
  StateProvince: 'import',
  Supervisor: 'ignore',
  'The Eight Dimensions of Wellness - Eight Dimensions of Wellness - Check all that apply':
    'import',
  'The Eight Dimensions of Wellness - Gambling Concerns': 'ignore',
  ThirdPartyAddress: 'ignore',
  ThirdPartyCity: 'ignore',
  ThirdPartyCounty: 'ignore',
  ThirdPartyName: 'ignore',
  ThirdPartyOrganization: 'ignore',
  ThirdPartyPhoneNumber: 'ignore',
  ThirdPartyPostalCode: 'ignore',
  ThirdPartyStateProvince: 'ignore',
  UpdatedBy: 'ignore',
  UpdatedByName: 'ignore',
  UpdatedByWorkerNum: 'ignore',
  UpdatedOn: 'ignore',
  VolIdentifier: 'ignore',
  VolunteerComments: 'ignore',
  WasHangup: 'import',
  WasPrankCall: 'import',
  WasRealCall: 'import',
  WasSexCall: 'import',
  WasSilentCall: 'import',
  WasWrongNumber: 'import',
  CallReportNum: 'ignore',
  TextField2: 'ignore',
  TextField3: 'ignore',
  TextField4: 'ignore',
  TextField5: 'ignore',
  TextField6: 'ignore',
  TextField7: 'ignore',
  TextField8: 'ignore',
  TextField9: 'ignore',
  TextField10: 'ignore',
};

// Known source values per enumerable field, compared case-insensitively and trimmed; covers values already handled and ones still blocked on a decision.
export const KNOWN_FIELD_VALUES: Readonly<Record<string, ReadonlySet<string>>> = {
  'Caller Demographics - Age Range': new Set(['18-24', '25-40', '41-54', '55+']),
  'Caller Demographics - Ethnicity': new Set([
    'Hispanic/Latino',
    'Non Hispanic/Non Latino',
  ]),
  'Caller Demographics - Gender': new Set([
    'Male',
    'Female',
    'Non-binary',
    'Transgender',
    'Did not ask/Did not disclose',
  ]),
  'Caller Demographics - Pronouns': new Set([
    'He/him/his',
    'She/her/hers',
    'They/them',
    'other',
  ]),
  'Caller Demographics - Race': new Set([
    'Caucasian',
    'African American',
    'Asian',
    'American Indian',
    'Native Hawaiian or Other Pacific Islander',
    'other',
  ]),
  'Caller Demographics - Military Status': new Set(['Active', 'Retired', 'Non-Military']),
  'Incoming Call Information - How did you hear about the Warmline?': new Set([
    'Previously contacted',
    'Another Warm/Crisis line',
    'Internet Search',
    'Family/Friend',
    'Does Not Apply N/A',
    'Mental Health Provider',
    'Other',
    'Hospital/Health Practitioner',
    'Social Service Agency',
    'Radio/TV/Billboard',
    'Social Media',
    'Printed Materials',
  ]),
  'Caller Demographics - 988 referral': new Set(['Yes', 'No']),
  'Call Information - Call Type': new Set([
    'Crisis',
    'Non-Crisis',
    'Prank Call/Hang-up Call/Wrong Number/Voicemail',
  ]),
  'Referrals - Type of Resource': new Set([
    '988',
    'Behavioral Health',
    'Dental',
    'Employment',
    'FindHelp',
    'Food',
    'Hub',
    'Medical',
    'Other',
    'PRN',
    'Peer Support Specialist',
    'Respite',
    'Shelter',
    'Some Other Phone Line',
    'Some Other Website',
    'TeenLine',
    'Vision',
    'Warmline.org',
  ]),
  'The Eight Dimensions of Wellness - Eight Dimensions of Wellness - Check all that apply':
    new Set([
      'Emotional/Mental',
      'Environmental',
      'Financial',
      'Intellectual',
      'Occupational',
      'Physical',
      'Social',
      'Spiritual',
      'Does Not Apply N/A',
    ]),
};

// Fields in KNOWN_FIELD_VALUES whose raw value is a semicolon-separated multiselect.
export const MULTISELECT_VALUE_FIELDS: ReadonlySet<string> = new Set([
  'Referrals - Type of Resource',
  'The Eight Dimensions of Wellness - Eight Dimensions of Wellness - Check all that apply',
]);
