--- COSTS ---
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Free-en', 'Free', 'en', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Free-fr', 'Gratuit', 'fr', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Sliding Scale Baed on Eligibility-en', 'Sliding Scale Baed on Eligibility', 'en', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Sliding Scale Baed on Eligibility-fr', 'Coût pour service', 'fr', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Membership Fee-en', 'Membership Fee', 'en', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Membership Fee-fr', 'Cotisation de membre', 'fr', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'One-Time Small Fee-en', 'One-Time Small Fee', 'en', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'One-Time Small Fee-fr', 'Un seul paiement à prix modique', 'fr', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Cost Unknown-en', 'Cost Unknown', 'en', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Cost Unknown-fr', 'Coût inconnu', 'fr', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Covered by Health Insurance-en', 'Covered by Health Insurance', 'en', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-fee-structure-source', 'Covered by Health Insurance-fr', 'Couvert par l''assurance maladie', 'fr', null);


INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-how-is-service-offered', 'In-Person Support-en', 'In-Person Support', 'en', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-how-is-service-offered', 'In-Person Support-fr', 'Soutien en personne', 'fr', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-how-is-service-offered', 'Online Support-en', 'Online Support', 'en', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-how-is-service-offered', 'Online Support-fr', 'Soutien en ligne', 'fr', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-how-is-service-offered', 'Phone Support-en', 'Phone Support', 'en', null);
INSERT INTO resources."ResourceReferenceStringAttributeValues" ("accountSid", "list", "id", "value", "language", "info") VALUES ('ACd8a2e89748318adf6ddff7df6948deaf', 'khp-how-is-service-offered', 'Phone Support-fr', 'Soutien par téléphone', 'fr', null);