services:
  db:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - hrm_postgres_volume:/var/lib/postgresql
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  hrm_postgres_volume: { }