name: Check License Header

on: [push]

jobs:
  license-header:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Validate License Headers
        run: npm run license:check
